// Use wit_bindgen to generate the traits and structs from the WIT file
wit_bindgen::generate!({
    path: "../../wit/gobbler.wit",
    world: "gobbler",
});

struct Plugin;

// We implement the `Guest` trait generated by wit-bindgen for the `parser` interface
impl exports::filegoblin::plugin::parser::Guest for Plugin {
    fn gobble(data: Vec<u8>, extension: String) -> Result<String, String> {
        // Our "dummy" logic: Only parse `.gob` or `.csv` files for testing.
        if extension != ".gob" && extension != "gob" && extension != ".csv" && extension != "csv" {
            return Err(format!("Dummy Plugin only parses '.gob' or '.csv' files, got: {}", extension));
        }

        // We assume `.gob` files are just UTF-8 strings wrapped in asterisks
        match String::from_utf8(data) {
            Ok(s) => {
                let markdown = format!("## DUMMY PARSER HIT!\n\n***\n{}\n***", s);
                Ok(markdown)
            }
            Err(e) => Err(format!("Dummy Plugin failed UTF-8 conversion: {}", e)),
        }
    }
}

// Export the plugin struct to the WASM ABI
export!(Plugin);
